services:
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env.postgres
    networks:
      - hasura-network

  hasura:
    image: hasura/graphql-engine:v2.36.8
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    env_file:
      - .env.hasura
    networks:
      - hasura-network

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - ./ssl:/etc/nginx/ssl:ro
    env_file:
      - .env.nginx
    depends_on:
      - hasura
    networks:
      - hasura-network

volumes:
  db_data:

networks:
  hasura-network:
    driver: bridge
